configName: ssd1963_rgb565_mxt_e54
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: bsp;core;core_apps_pic32mz_da;core_apps_sam_9x60;core_apps_sam_a5d2;core_apps_sam_e70_s70_v70_v71;csp;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_sam_9x60;csp_apps_sam_a5d2;csp_apps_sam_e70_s70_v70_v71;Devices;dev_packs;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;gfx_apps_sam_9x60;gfx_apps_sam_a5d2;gfx_apps_sam_c20_c21;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_apps_sam_l22;harmony-services;quick_docs;touch;usb;usb_apps_device;usb_apps_host
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAME54_DFP\3.8.234
