configName: ili9488_rgb565_e54_cult_parallel_iar
folderName: legato_qs_e54_cult_cpro_parallel.IAR
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: legato_qs_e54_cult_cpro_parallel.IAR
settings:
  PackageFilter: audio;bsp;core;core_apps_pic32mz_da;core_apps_pic32mz_ef;crypto;cryptoauthlib;csp;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;gfx;gfx_apps;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;gfx_apps_sam_9x60;gfx_apps_sam_a5d2;gfx_apps_sam_c20_c21;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_old;net;net_apps_sam_e70_v71;quick_docs;touch;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.5.87\atdf\ATSAME54P20A.atdf
